### PR TITLE
Add rosserial package w/ hacked support for Teensy 4.0

### PR DESCRIPTION
**Pull request by baronep**
Pulled the latest package from melodic-devel and then applied this patch manually

https://github.com/ros-drivers/rosserial/pull/456

### CODE REVIEW

**Comment by thegenialschemer** [comment]
Is including the packages into the repo the best way to add other packages into our project? Can we explore submodules or [Git LFS](https://git-lfs.github.com/) I just don't remember what the best pattern is. I think it's a little weird to have our source code mixed in with others. It will make code reviews a little more difficult to parse through.

**Comment by nxydes** [comment]
> Is including the packages into the repo the best way to add other packages into our project? Can we explore submodules or [Git LFS](https://git-lfs.github.com/) I just don't remember what the best pattern is. I think it's a little weird to have our source code mixed in with others. It will make code reviews a little more difficult to parse through.

Yea its very common in all the robot projects I've worked on. The reasons include modifying the code for our purposes (like patrick did here) and keeping known working state of the code from breaking on future updates. The breaking problem is pretty common given its an open source project.

**Comment by nxydes** [comment]
This look good to me. The one change is simple and makes sense.

**Comment by baronep** [comment]
To your point Ian, submodules might work, but I think in order for that to be effective we would need to maintain our own fork of the original repo which seemed like a lot of work for a project with almost nothing in it yet haha

**Pull request merged**
